name: CI

on: # trigger
  workflow_dispatch: # manual button to run this workflow

  push:
    branches:
      - main
    paths:
      - 'src/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Show trigger
        run: echo "Triggered by ${{ github.event_name }}"

      - name: Run tests
        run: echo "Tests passed"

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build application
        run: |
          mkdir -p dist
          cp src/index.html dist/index.html
