name: CI

on: # trigger
  workflow_dispatch: # manual button to run this workflow

jobs:
  hello: # name of our job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7 # use pre built checkout action here

      - name: Show environment
        run: |
          echo "Hello from GitHub Actions" # print something
          uname -a # name of the OS
          pwd # print the working directory / folder

      - name: List files
        run: ls -la

      - name: Show index.html contents
        run: cat src/index.html
